language: scala
jdk:
- oraclejdk7
- oraclejdk8
scala:
- 2.10.4
- 2.11.4
script:
- sbt ++$TRAVIS_SCALA_VERSION -J-XX:+CMSClassUnloadingEnabled -J-XX:+UseConcMarkSweepGC testAll
before_install:
- npm install -g karma-cli bower
- npm install
- bower install
