language: scala
jdk:
- oraclejdk7
- oraclejdk8
scala:
- 2.10.4
- 2.11.2
sbt_args: -J-XX:+CMSClassUnloadingEnabled -J-XX:+UseConcMarkSweepGC
before_install:
  - npm install -g karma-cli bower
  - npm install
  - bower install
